### ISSUE TITLE
Settup the capture of Data from Create/Edit item form

### ISSUE THREAD

**Issue by mark-e-brewer** [NSS-Evening-E22/pos-system-outlaw-bandanas#15]
-Settup the correct form events on create/edit item for so that the information filled out on the form is added to an object.
-the even and object created is different for edit and submit. 
-the object that the form info is added to will be POSTed or PATCHed depending on if Submit or Edit
-this ticket is intertwined with the "Submit button on create/edit item form" 
-(the api for update and create item are mentioned in "Submit button on create/edit item form" but could also be created here)
# dependencies
#8
#9 
#11 
#13 
#20

**Comment by SteveCButler** [comment]
complete
