### ISSUE TITLE
Submit Button on create/edit item form functionality

### ISSUE THREAD

**Issue by mark-e-brewer** [NSS-Evening-E22/pos-system-outlaw-bandanas#16]
-Create and API call for 'CreatingItem' and 'UpdateItem' that is used on Submit/Edit item form button click
-on submit info entered should POST to database in an object that is in a form event.
-on edit info changed should PATCH the current item with an object.
-the button should also take the user to the Order Details page.
-this ticket is intertwined with the "Settup capture of Data from create/edit item form" 
# dependencies
#8
#9 
#11 
#13 
#20

**Comment by SteveCButler** [comment]
complete
